### ISSUE TITLE
integrating cusom models

### ISSUE THREAD

**Issue by delray** [ioannismihailidis/venvBuilderTD#1]
Hi,
this is a great tool - I've got it working here on my end with the supplied detection/segmentation models, but now I am trying to adapt it to a custom pose classification model for a project I'm working on. The model and the python code work from a terminal, but integrating into your framework is a bit tricky. Not sure where its best to ask questions - here or the TD forum?

**Comment by hello-elastique** [comment]
Hi @delray,
thanks for using this tiny project. Is it a custom yolo model or based on another model?

**Comment by ioannismihailidis** [comment]
Hi @delray,
thanks for using this tiny project. Is it a custom yolo model or based on another model?

**Comment by delray** [comment]
well its a fine tuned yolov8 model, so I assumed it would work, but the TD integration is new for me. The code I'm using is here: [https://github.com/delray/PoseClassifier-yolo]

**Comment by ioannismihailidis** [comment]
You can modify the example "YoloV8Detection" quite easy. Make sure that its running with issues.

First add you custom model (.pt file has to be in your project folder) to DAT table_yolo__models.
![image](https://github.com/user-attachments/assets/9f5e5e7d-d85b-4c8a-b9ad-0cc0b51e49f2)

This  will allow you to select you custom model in the parameters:
![image](https://github.com/user-attachments/assets/58f6bda2-00c2-4d2f-8986-6b1a217c5928)

Enable/Disable the tox will load your custom model.

Passing a new image to a inference function is already provided with the TOP on cook function:
![image](https://github.com/user-attachments/assets/24c09895-427a-4660-b451-b408415915df)

The example inferene function is in "YOLOv8OnnxExt" and shows how to use the model data in various ways and e.g. pass the date to a DAT:

![image](https://github.com/user-attachments/assets/46e695b5-5334-4a7f-ab39-1c74d3873229)

THIS is the place where you should place your terminal inference code.

At the moment the code is missing color channel swap because TD and pytorch need different channels orders. You maaay could run into detection errors.

**Comment by delray** [comment]
yeah, I have that figured out, but i guess Im just trying to wort out the order of things between the cuda top, script and the actual yolo code. I think i'm getting close, just trying to squash errors. The inference and what is returned is quite a bit different for pose classification vs detection.

**Comment by delray** [comment]
I got it all working here, and then restarted my PC, and reopend the toe file, but I got an odd error upon opening.

Any clues?

`Traceback (most recent call last):
  File "/YoloV8DetectionCudatop/script1_callbacks", line 4
    r = previousimport(*args, **kw)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mb\AppData\Roaming\Python\Python311\site-packages\numpy\__init__.py", line 112
    _delvewheel_patch_1_5_2()
  File "C:\Users\mb\AppData\Roaming\Python\Python311\site-packages\numpy\__init__.py", line 109, in _delvewheel_patch_1_5_2
    os.add_dll_directory(libs_dir)
  File "<frozen os>", line 1119, in add_dll_directory
FileNotFoundError: [WinError 206] The filename or extension is too long: 'C:\\Users\\mb\\AppData\\Roaming\\Python\\Python311\\site-packages\\numpy.libs'`
