### ISSUE TITLE
tensorRT engine building

### ISSUE THREAD

**Issue by delray** [ioannismihailidis/venvBuilderTD#2]
Hi Again,
I tried using the export TensorRT method and it exported the engine without errors.

When trying to use it, I got the following error:
```
Using device: cuda
Loading model from yolov8n.engine
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify','pose' or 'obb'.
Loading yolov8n.engine for TensorRT inference...
SetupCudaTop
Using device: cuda
Loading model from yolov8n.engine
Loading yolov8n.engine for TensorRT inference...
SetupCudaTop
As Tensor. Duration: 0.0000 ms

```
So I added the following to the model loading:
`self.model = YOLO(modelName, task='detect')`
so the error goes away, but unfortunately I dont get any detections in either the annotated_image or in the DAT table.

if a change it to 'classify'
```
AttributeError: 'NoneType' object has no attribute 'cls'
Traceback (most recent call last):
  File "/project1/YoloV8DetectionCudatop/script1_callbacks", line 34, in onCook
  File "/project1/YoloV8DetectionCudatop/YoloV8DetectionCudatop", line 119, in DetectYolo
  File "D:\venvBuilderTD\samples\yolov8_detection_cudatop\venv-yolov8-cudatop\Lib\site-packages\supervision\detection\core.py", line 270, in from_ultralytics
    class_id = ultralytics_results.boxes.cls.cpu().numpy().astype(int)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cls'

```
thanks in advance!

**Comment by Dartayous** [comment]
Hello, delray,

My name is Dartayous and I saw that you had some issues with supervision.from_ultralytics()  failure because results.boxes is None. I wanted to take a crack at trying to figure out the issue. I know this issue was opened back in 2024, but just in case you are still having the issue, I might have a solution for you.

I tested a clean YOLOv8 TensorRT export/inference path on Ubuntu with NVIDIA GPU/CUDA and was able to get valid detections from the .engine model.

Working pattern:
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.export(
      format="engine",
      imgsz=640,
      device=0,
      half=False,
      dynamic=False,
      simplify=True,
)

engine_model = YOLO("yolov8n.engine", task="detect")
results = engine_model("images/bus.jpg", imgsz=640, conf=0.25, device=0)

boxes = results[0].boxes
print("boxes is None:", boxes is None)
print("num detections:", 0 if boxes is None else len(boxes))

On my system this returned:
boxes is None: False
num detections: 5

So if results.boxes is coming back as None, I would first check:
    1. Whether the original .pt model detects objects on the same input image.
    2. Whether the TensorRT engine was exported with the same imgsz used during inference.
    3. Whether task="detect" is explicitly passed when loading the .engine.
    4. Whether the confidence threshold is too high.
    5. Whether the post-processing wrapper safely handles empty detections before calling supervision.from_ultralytics().

This suggests the issue may be export/inference configuration rather than TensorRT itself failing. Of course, I’m hoping this isn't a result if “works on my machine syndrome”, but I think this fix is universal.  

One extra interesting result I found (pertaining to #1) was even though .pt was slower than .engine, it also picked up one more object. It was a “stop sign” that was not a stop sign, but the fact that its trying to see more is interesting.

Anyway, thank you for posting this issue. I’m on the hunt to learn ever more about computer vision and machine learning, so this was an excellent bug to deep dive into and I hope it also helps you out. 

Lesson Learned,
Dartayous
